# Configuraci�n de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/balance
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci�n de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:sql/data.sql
spring.jpa.defer-datasource-initialization=true


# Configuraci�n de seguridad
app.security.jwt.secret=babynomellamesqueyoestoyocupadaescuchandomimales9432894239r043
app.security.jwt.expirationMs=86400000

# Configuraci�n de logging
logging.level.root=INFO
logging.level.com.wellbeing.deviceusage=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always